package org.itp.service.scheduling;

import com.mysql.jdbc.Connection;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Kavinda
 */
public class jobupdate extends javax.swing.JFrame {

    Connection con2 = DBconnect.connect();
    PreparedStatement pst;
    String sqlq, sql2, sql3;
    ResultSet rs1;
    int jobb;
    double gpr, spr = 800;
    DecimalFormat df = new DecimalFormat("#.00");
    String datee;
    //double gpr, spr = 800;
    int eTotavil = 0, assign = 0, eAva = 0;
    //DecimalFormat df = new DecimalFormat("#.00");

    /**
     * Creates new form jobschedulemain
     */
    //Connection con2= DBconnect.connect();
    public jobupdate() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    public jobupdate(int jno) {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        jobb = jno;

        //single price is 115% of the employees' salary
/*        sqlq = "select salary as sal from employees where status='working'";
        try {
            pst = con2.prepareStatement(sqlq);
            //int eavailable=
            rs1 = pst.executeQuery(sqlq);
            System.out.println(rs1);

            if (rs1.next()) {
                spr = rs1.getInt("sal");
            }
            

            //System.out.println(sqlq);
        } catch (Exception e) {
            System.err.print(e);
            jOptionPane1.showMessageDialog(rootPane, "failed to load the employee salary", "Error", JOptionPane.WARNING_MESSAGE);
        }
         */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ji = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnChk = new javax.swing.JButton();
        btnUd = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        dt = new javax.swing.JTextField();
        ea = new javax.swing.JTextField();
        lc = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        gp = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("previous details");
        jLabel1.setToolTipText("");

        jLabel2.setText("job ID");
        jLabel2.setToolTipText("");

        jLabel3.setText("date");
        jLabel3.setToolTipText("");

        ji.setToolTipText("");
        ji.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ji.setEnabled(false);
        ji.setName("ji"); // NOI18N

        jButton1.setText("Back");
        jButton1.setToolTipText("");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        btnChk.setText("Check availability");
        btnChk.setEnabled(false);
        btnChk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChkActionPerformed(evt);
            }
        });

        btnUd.setText("Update job");
        btnUd.setEnabled(false);
        btnUd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUdActionPerformed(evt);
            }
        });

        jTextField3.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField3.setEnabled(false);

        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField4KeyReleased(evt);
            }
        });

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField5KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField5KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });

        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField6KeyReleased(evt);
            }
        });

        jLabel5.setText("new job details");
        jLabel5.setToolTipText("");

        jLabel6.setText("Date");
        jLabel6.setToolTipText("");

        jLabel7.setText("place");
        jLabel7.setToolTipText("");

        jLabel8.setText("No. of employees needed");
        jLabel8.setToolTipText("");

        jLabel9.setText("No. of employees available");
        jLabel9.setToolTipText("");

        dt.setToolTipText("");
        dt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        dt.setEnabled(false);
        dt.setName("dt"); // NOI18N

        ea.setToolTipText("");
        ea.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ea.setEnabled(false);
        ea.setName("ea"); // NOI18N

        lc.setToolTipText("");
        lc.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        lc.setEnabled(false);
        lc.setName("lc"); // NOI18N

        jLabel10.setText("employees assigned");
        jLabel10.setToolTipText("");

        jLabel11.setText("location");
        jLabel11.setToolTipText("");

        jLabel12.setText("gross price");
        jLabel12.setToolTipText("");

        gp.setToolTipText("");
        gp.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        gp.setEnabled(false);
        gp.setName("gp"); // NOI18N

        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel4.setText("gross price ");

        jTextField1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField1.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUd)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                                    .addComponent(jTextField1))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnChk)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                    .addComponent(jTextField5)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(106, 106, 106)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(59, 59, 59)
                                            .addComponent(jLabel11)))
                                    .addGap(18, 18, 18))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(67, 67, 67)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3))
                                    .addGap(18, 18, 18)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dt, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ji, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lc, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ea, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(gp, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel1)))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton1)
                .addGap(3, 3, 3)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnChk))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(ji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2)))
                                    .addComponent(jLabel1))
                                .addGap(31, 31, 31))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(dt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(lc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(0, 26, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(btnUd)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        this.dispose();
        jobschedulemain sh1 = new jobschedulemain();
    }//GEN-LAST:event_jButton1MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        String jsid = Integer.toString(jobb);
        System.out.println("dddddd");
        //if(jsid.isEmpty())

        sqlq = "select * from jobs where jobid=" + jsid;
        try {
            pst = con2.prepareStatement(sqlq);
            //int eavailable=
            rs1 = pst.executeQuery(sqlq);
            System.out.println(rs1);

            if (rs1.next()) {
                ji.setText(rs1.getString(1));
                dt.setText(rs1.getString(4));//System.out.println(rs1.getString(4));
                lc.setText(rs1.getString(3));
                ea.setText(rs1.getString(5));
                gp.setText(rs1.getString(6));
                //jButton4.setEnabled(true);
            } else {
                //jButton4.setEnabled(false);
                jOptionPane1.showMessageDialog(rootPane, "job not found", "Error", JOptionPane.ERROR_MESSAGE);
                //setNull();
            }
            //System.out.println(sqlq);
        } catch (Exception e) {
            System.err.print(e);
            jOptionPane1.showMessageDialog(rootPane, "Job not found");
            //jButton4.setEnabled(false);
            //setNull();
        }
    }//GEN-LAST:event_formWindowOpened

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed

    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        // TODO add your handling code here:


    }//GEN-LAST:event_jTextField5KeyTyped

    private void jTextField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField5KeyPressed

    private void jTextField5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyReleased

        for (int i = 0; i < jTextField5.getText().length(); i++) {
            if (!(Character.isDigit(jTextField5.getText().charAt(i)))) {
                jTextField5.setForeground(Color.red);
                //jButton2.setEnabled(false);
                //jButton4.setEnabled(false);
                //jLabel4.setVisible(true);
                jOptionPane1.showMessageDialog(rootPane, "Enter only digits in this field", "error", JOptionPane.WARNING_MESSAGE);
                jTextField5.setText("");
                jTextField5.setForeground(Color.BLACK);
                return;
            }
        }
        btnChk.setEnabled(true);
        //jLabel4.setVisible(false);

        boolean tb4 = !(jTextField4.getText().isEmpty()); //true if empty
        boolean tb6 = !(jTextField6.getText().isEmpty());
        boolean tb5 = !(jTextField5.getText().isEmpty());

        if (tb5 && tb6 && tb4) {
            btnChk.setEnabled(true);
        } else {
            btnChk.setEnabled(false);
        }
    }//GEN-LAST:event_jTextField5KeyReleased

    private void jTextField6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyReleased
        // TODO add your handling code here:
        boolean tb4 = !(jTextField4.getText().isEmpty()); //true if empty
        boolean tb6 = !(jTextField6.getText().isEmpty());
        boolean tb5 = !(jTextField5.getText().isEmpty());

        if (tb5 && tb6 && tb4) {
            btnChk.setEnabled(true);
        } else {
            btnChk.setEnabled(false);
        }
    }//GEN-LAST:event_jTextField6KeyReleased

    private void jTextField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyReleased
        // TODO add your handling code here:
        boolean tb4 = !(jTextField4.getText().isEmpty()); //true if empty
        boolean tb6 = !(jTextField6.getText().isEmpty());
        boolean tb5 = !(jTextField5.getText().isEmpty());

        if (tb5 && tb6 && tb4) {
            btnChk.setEnabled(true);
        } else {
            btnChk.setEnabled(false);
        }
    }//GEN-LAST:event_jTextField4KeyReleased

    private void btnChkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChkActionPerformed
        datee = jTextField4.getText();
        sqlq = "SELECT sum(empass) as ta FROM empassigned where jdate='" + datee + "'";

        //employees in leave in that date
        sql2 = "SELECT count(l.empid) as tl FROM leavek l where l.date='" + datee + "'";

        //total employees working
        String sql3 = "select count(*) as tot from employee where Current_Status='working'";
        try {
            //total employees working
            pst = con2.prepareStatement(sql3);
            rs1 = pst.executeQuery(sql3);
            //int eTotavil = 0;
            if (rs1.next()) {
                eTotavil = rs1.getInt("tot");
                System.out.println(eTotavil);
            }

            //employees assigned in other jobs  at that date
            pst = con2.prepareStatement(sqlq);
            rs1 = pst.executeQuery(sqlq);
            int eAssignedOther = 0;
            if (rs1.next()) {
                eAssignedOther = rs1.getInt("ta");
                System.out.println(eAssignedOther);
            }

            //employees in leave in that date
            pst = con2.prepareStatement(sql2);
            rs1 = pst.executeQuery(sql2);
            int eLeave = 0;
            if (rs1.next()) {
                eLeave = rs1.getInt("tl");
                System.out.println(eLeave);
            }

            //Final available employees
            eAva = eTotavil - eLeave - eAssignedOther;
            if (eAva < 0) {
                eAva = 0;
            }

            System.out.println(eAva);
            jTextField3.setText(Integer.toString(eAva));

            //System.out.println(sqlq);
        } catch (Exception e) {
            System.err.print(e);
            return;
        }
        //availabity confirm nm vitharak
        gpr = spr * Double.parseDouble(jTextField5.getText()) * 1.15;
        
        jTextField1.setText(df.format(gpr));
        btnUd.setEnabled(true);
    }//GEN-LAST:event_btnChkActionPerformed

    private void btnUdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUdActionPerformed
        // jobupdate
        //UPDATE table_name SET column1=value1,column2=value2,... WHERE some_column=some_value;
        String jjid=ji.getText();
        String dtt = jTextField4.getText();
        String plc = jTextField6.getText();
        String eneed = jTextField5.getText();
        gpr = Double.parseDouble(eneed) * spr * 1.15;

        try {
            //release assigned employees
            sqlq = "delete FROM empassigned where jobId=" + jjid ;
            pst = con2.prepareStatement(sqlq);
            pst.execute(sqlq);

            //employees in leave in that date
            //sql2 = "SELECT count(l.empid) as tl FROM leavek l where l.date='" + datee + "'";

            //total employees working
            //sql3 = "select count(*) as tot from employee where Current_Status='working'";
            
            if(Integer.parseInt(eneed)<=eAva)
                sql3 = "insert into empassigned values("+jjid+",'" + dtt + "',"+eneed+");";
            else
                sql3 = "insert into empassigned values("+jjid+",'" + dtt + "',"+eAva+");";
            System.out.println("EmpAss: "+sql3);
            
            pst = con2.prepareStatement(sql3);
            pst.execute(sql3);
            
        } catch (Exception e) {
            System.out.println(e);
            return;
        }

        sqlq = "update jobs set location='" + plc + "', date='" + dtt + "', emp=" + eneed + ", gprice=" + gpr + " where jobid=" + jobb;

        int rep = jOptionPane1.showConfirmDialog(rootPane, "Are you sure you want ot update this job?", "Confirm", JOptionPane.YES_NO_CANCEL_OPTION);
        if (rep == JOptionPane.YES_OPTION) {
            try {

                pst = con2.prepareStatement(sqlq);
                pst.execute(sqlq);
                jOptionPane1.showMessageDialog(rootPane, "Job updated successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                new jobupdate(jobb);
                this.dispose();

            } catch (Exception e) {
                System.err.print(e);
                jOptionPane1.showMessageDialog(rootPane, "Job update failed", "Error", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
    }//GEN-LAST:event_btnUdActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField3.setText("");
        jTextField1.setText("");
        btnChk.setEnabled(false);
        btnUd.setEnabled(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jobschedulemain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jobschedulemain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jobschedulemain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jobschedulemain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jobschedulemain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChk;
    private javax.swing.JButton btnUd;
    private javax.swing.JTextField dt;
    private javax.swing.JTextField ea;
    private javax.swing.JTextField gp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField ji;
    private javax.swing.JTextField lc;
    // End of variables declaration//GEN-END:variables
}
