package org.itp.service.scheduling;

import com.mysql.jdbc.Connection;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Kavinda
 */
public class jobupdate extends javax.swing.JFrame {

    Connection con2 = DBconnect.connect();
    PreparedStatement pst;
    String sqlq, sql2, sql3;
    ResultSet rs1;
    int jobb;
    double gpr, spr = 800;
    DecimalFormat df = new DecimalFormat("#.00");
    String datee;
    //double gpr, spr = 800;
    int eTotavil = 0, assign = 0, eAva = 0;
    //DecimalFormat df = new DecimalFormat("#.00");

    /**
     * Creates new form jobschedulemain
     */
    //Connection con2= DBconnect.connect();
    public jobupdate() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    public jobupdate(int jno) {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        jobb = jno;

        //single price is 115% of the employees' salary
/*        sqlq = "select salary as sal from employees where status='working'";
        try {
            pst = con2.prepareStatement(sqlq);
            //int eavailable=
            rs1 = pst.executeQuery(sqlq);
            System.out.println(rs1);

            if (rs1.next()) {
                spr = rs1.getInt("sal");
            }
            

            //System.out.println(sqlq);
        } catch (Exception e) {
            System.err.print(e);
            jOptionPane1.showMessageDialog(rootPane, "failed to load the employee salary", "Error", JOptionPane.WARNING_MESSAGE);
        }
         */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ji = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnChk = new javax.swing.JButton();
        btnUd = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        dt = new javax.swing.JTextField();
        ea = new javax.swing.JTextField();
        lc = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        gp = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jdate = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("previous details");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 86, -1, -1));

        jLabel2.setText("job ID");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 115, -1, -1));

        jLabel3.setText("date");
        jLabel3.setToolTipText("");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 146, -1, -1));

        ji.setToolTipText("");
        ji.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ji.setEnabled(false);
        ji.setName("ji"); // NOI18N
        getContentPane().add(ji, new org.netbeans.lib.awtextra.AbsoluteConstraints(527, 112, 105, -1));

        jButton1.setText("Back");
        jButton1.setToolTipText("");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 19, 57, -1));

        btnChk.setText("Check availability");
        btnChk.setEnabled(false);
        btnChk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChkActionPerformed(evt);
            }
        });
        getContentPane().add(btnChk, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 250, -1, -1));

        btnUd.setText("Update job");
        btnUd.setEnabled(false);
        btnUd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUdActionPerformed(evt);
            }
        });
        getContentPane().add(btnUd, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 361, -1, -1));

        jTextField3.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField3.setEnabled(false);
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 291, 69, -1));

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField5KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField5KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 161, 118, -1));

        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField6KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 131, 118, -1));

        jLabel5.setText("new job details");
        jLabel5.setToolTipText("");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 86, -1, -1));

        jLabel6.setText("Date");
        jLabel6.setToolTipText("");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 111, -1, -1));

        jLabel7.setText("place");
        jLabel7.setToolTipText("");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 134, -1, -1));

        jLabel8.setText("No. of employees needed");
        jLabel8.setToolTipText("");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 157, 144, 28));

        jLabel9.setText("No. of employees available");
        jLabel9.setToolTipText("");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 294, -1, -1));

        dt.setToolTipText("");
        dt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        dt.setEnabled(false);
        dt.setName("dt"); // NOI18N
        getContentPane().add(dt, new org.netbeans.lib.awtextra.AbsoluteConstraints(527, 143, 105, -1));

        ea.setToolTipText("");
        ea.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ea.setEnabled(false);
        ea.setName("ea"); // NOI18N
        getContentPane().add(ea, new org.netbeans.lib.awtextra.AbsoluteConstraints(527, 201, 105, -1));

        lc.setToolTipText("");
        lc.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        lc.setEnabled(false);
        lc.setName("lc"); // NOI18N
        getContentPane().add(lc, new org.netbeans.lib.awtextra.AbsoluteConstraints(527, 175, 105, -1));

        jLabel10.setText("employees assigned");
        jLabel10.setToolTipText("");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 201, -1, -1));

        jLabel11.setText("location");
        jLabel11.setToolTipText("");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 178, -1, -1));

        jLabel12.setText("gross price");
        jLabel12.setToolTipText("");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 227, -1, -1));

        gp.setToolTipText("");
        gp.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        gp.setEnabled(false);
        gp.setName("gp"); // NOI18N
        getContentPane().add(gp, new org.netbeans.lib.awtextra.AbsoluteConstraints(527, 227, 105, -1));

        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 45, -1, -1));

        jLabel4.setText("gross price ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 322, -1, -1));

        jTextField1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField1.setEnabled(false);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 322, 69, -1));

        jdate.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(jdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 105, 118, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itp/image/log.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 460, 60));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itp/image/b2.jpg"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        this.dispose();
        jobschedulemain sh1 = new jobschedulemain();
    }//GEN-LAST:event_jButton1MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try {
            sqlq = "select basicSalary as BS from salary where RoleID=4";
            pst = con2.prepareStatement(sqlq);
            rs1 = pst.executeQuery(sqlq);
            //int eTotavil = 0;
            if (rs1.next()) {
                spr = rs1.getDouble("BS");
                spr=spr/30.0;
                System.out.println(spr);
            }

        } catch (Exception e) {
            System.out.println(e);
        }
        String jsid = Integer.toString(jobb);
        System.out.println("dddddd");
        //if(jsid.isEmpty())

        sqlq = "select * from jobs where jobid=" + jsid;
        try {
            pst = con2.prepareStatement(sqlq);
            //int eavailable=
            rs1 = pst.executeQuery(sqlq);
            System.out.println(rs1);

            if (rs1.next()) {
                ji.setText(rs1.getString(1));
                dt.setText(rs1.getString(4));//System.out.println(rs1.getString(4));
                lc.setText(rs1.getString(3));
                ea.setText(rs1.getString(5));
                gp.setText(rs1.getString(6));
                //jButton4.setEnabled(true);
            } else {
                //jButton4.setEnabled(false);
                jOptionPane1.showMessageDialog(rootPane, "job not found", "Error", JOptionPane.ERROR_MESSAGE);
                //setNull();
            }
            //System.out.println(sqlq);
        } catch (Exception e) {
            System.err.print(e);
            jOptionPane1.showMessageDialog(rootPane, "Job not found");
            //jButton4.setEnabled(false);
            //setNull();
        }
    }//GEN-LAST:event_formWindowOpened

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed

    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        // TODO add your handling code here:


    }//GEN-LAST:event_jTextField5KeyTyped

    private void jTextField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField5KeyPressed

    private void jTextField5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyReleased

        for (int i = 0; i < jTextField5.getText().length(); i++) {
            if (!(Character.isDigit(jTextField5.getText().charAt(i)))) {
                jTextField5.setForeground(Color.red);
                //jButton2.setEnabled(false);
                //jButton4.setEnabled(false);
                //jLabel4.setVisible(true);
                jOptionPane1.showMessageDialog(rootPane, "Enter only digits in this field", "error", JOptionPane.WARNING_MESSAGE);
                jTextField5.setText("");
                jTextField5.setForeground(Color.BLACK);
                return;
            }
        }
        btnChk.setEnabled(true);
        //jLabel4.setVisible(false);

        boolean tb4 = !(((JTextField) jdate.getDateEditor().getUiComponent()).getText().isEmpty()); //true if empty
        boolean tb6 = !(jTextField6.getText().isEmpty());
        boolean tb5 = !(jTextField5.getText().isEmpty());

        if (tb5 && tb6 && tb4) {
            btnChk.setEnabled(true);
        } else {
            btnChk.setEnabled(false);
        }
    }//GEN-LAST:event_jTextField5KeyReleased

    private void jTextField6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyReleased
        // TODO add your handling code here:
        boolean tb4 = !(((JTextField) jdate.getDateEditor().getUiComponent()).getText().isEmpty()); //true if empty
        boolean tb6 = !(jTextField6.getText().isEmpty());
        boolean tb5 = !(jTextField5.getText().isEmpty());

        if (tb5 && tb6 && tb4) {
            btnChk.setEnabled(true);
        } else {
            btnChk.setEnabled(false);
        }
    }//GEN-LAST:event_jTextField6KeyReleased

    private void btnChkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChkActionPerformed
        datee = ((JTextField) jdate.getDateEditor().getUiComponent()).getText();
        sqlq = "SELECT sum(empass) as ta FROM empassigned where jdate='" + datee + "'";

        //employees in leave in that date
        sql2 = "SELECT count(l.empid) as tl FROM attendance l where l.work_date='" + datee + "' and presence='Absent'";

        //total employees working
        String sql3 = "select count(*) as tot from employee where Current_Status='working'";
        try {
            //total employees working
            pst = con2.prepareStatement(sql3);
            rs1 = pst.executeQuery(sql3);
            //int eTotavil = 0;
            if (rs1.next()) {
                eTotavil = rs1.getInt("tot");
                System.out.println(eTotavil);
            }

            //employees assigned in other jobs  at that date
            pst = con2.prepareStatement(sqlq);
            rs1 = pst.executeQuery(sqlq);
            int eAssignedOther = 0;
            if (rs1.next()) {
                eAssignedOther = rs1.getInt("ta");
                System.out.println(eAssignedOther);
            }

            //employees in leave in that date
            pst = con2.prepareStatement(sql2);
            rs1 = pst.executeQuery(sql2);
            int eLeave = 0;
            if (rs1.next()) {
                eLeave = rs1.getInt("tl");
                System.out.println(eLeave);
            }

            //Final available employees
            eAva = eTotavil - eLeave - eAssignedOther;
            if (eAva < 0) {
                eAva = 0;
            }

            System.out.println(eAva);
            jTextField3.setText(Integer.toString(eAva));

            //System.out.println(sqlq);
        } catch (Exception e) {
            System.err.print(e);
            return;
        }
        //availabity confirm nm vitharak
        gpr = spr * Double.parseDouble(jTextField5.getText()) * 1.15;
        
        jTextField1.setText(df.format(gpr));
        btnUd.setEnabled(true);
    }//GEN-LAST:event_btnChkActionPerformed

    private void btnUdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUdActionPerformed
        // jobupdate
        //UPDATE table_name SET column1=value1,column2=value2,... WHERE some_column=some_value;
        String jjid=ji.getText();
        String dtt = ((JTextField) jdate.getDateEditor().getUiComponent()).getText();
        String plc = jTextField6.getText();
        String eneed = jTextField5.getText();
        gpr = Double.parseDouble(eneed) * spr * 1.15;

        try {
            //release assigned employees
            sqlq = "delete FROM empassigned where jobId=" + jjid ;
            pst = con2.prepareStatement(sqlq);
            pst.execute(sqlq);

            //employees in leave in that date
            //sql2 = "SELECT count(l.empid) as tl FROM leavek l where l.date='" + datee + "'";

            //total employees working
            //sql3 = "select count(*) as tot from employee where Current_Status='working'";
            
            if(Integer.parseInt(eneed)<=eAva)
                sql3 = "insert into empassigned values("+jjid+",'" + dtt + "',"+eneed+", null, 'pending');";
            else
                sql3 = "insert into empassigned values("+jjid+",'" + dtt + "',"+eAva+", null, 'pending');";
            System.out.println("EmpAss: "+sql3);
            
            pst = con2.prepareStatement(sql3);
            pst.execute(sql3);
            
        } catch (Exception e) {
            System.out.println(e);
            return;
        }

        sqlq = "update jobs set location='" + plc + "', date='" + dtt + "', emp=" + eneed + ", gprice=" + gpr + " where jobid=" + jobb;

        int rep = jOptionPane1.showConfirmDialog(rootPane, "Are you sure you want ot update this job?", "Confirm", JOptionPane.YES_NO_CANCEL_OPTION);
        if (rep == JOptionPane.YES_OPTION) {
            try {

                pst = con2.prepareStatement(sqlq);
                pst.execute(sqlq);
                jOptionPane1.showMessageDialog(rootPane, "Job updated successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                new jobupdate(jobb);
                this.dispose();

            } catch (Exception e) {
                System.err.print(e);
                jOptionPane1.showMessageDialog(rootPane, "Job update failed", "Error", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
    }//GEN-LAST:event_btnUdActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        ((JTextField) this.jdate.getDateEditor().getUiComponent()).setText(null);
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField3.setText("");
        jTextField1.setText("");
        btnChk.setEnabled(false);
        btnUd.setEnabled(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jobschedulemain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jobschedulemain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jobschedulemain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jobschedulemain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jobschedulemain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChk;
    private javax.swing.JButton btnUd;
    private javax.swing.JTextField dt;
    private javax.swing.JTextField ea;
    private javax.swing.JTextField gp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private com.toedter.calendar.JDateChooser jdate;
    private javax.swing.JTextField ji;
    private javax.swing.JTextField lc;
    // End of variables declaration//GEN-END:variables
}
