package org.itp.finance.management;

import com.mysql.jdbc.ResultSetImpl;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import net.sf.jasperreports.web.actions.SearchData;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sumaduri 123
 */
public class CustomerBills extends javax.swing.JFrame {
    
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs=null;
    
    public CustomerBills(){
           initComponents();
           
           conn = dbconnec.connect();
    }

   

    /**
     * Creates new form finance3
     */
   

     











    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        cname = new javax.swing.JLabel();
        cnbx = new javax.swing.JTextField();
        cid = new javax.swing.JLabel();
        cidbx = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        bp = new javax.swing.JLabel();
        bpbx = new javax.swing.JTextField();
        sb = new javax.swing.JLabel();
        noj = new javax.swing.JLabel();
        nojbx = new javax.swing.JTextField();
        cc = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Ccbx = new javax.swing.JTextArea();
        ta = new javax.swing.JLabel();
        tabx = new javax.swing.JTextField();
        bd = new javax.swing.JLabel();
        bdbx = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        bck = new javax.swing.JButton();
        sbbx = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Customer Bills");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 96, 170, 45));

        cname.setText("Customer Name.");
        getContentPane().add(cname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 185, 105, -1));
        getContentPane().add(cnbx, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 179, 383, -1));

        cid.setText("Customer ID.");
        getContentPane().add(cid, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 226, 105, -1));

        cidbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidbxActionPerformed(evt);
            }
        });
        getContentPane().add(cidbx, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 220, 383, -1));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 352, -1, -1));

        bp.setText("Billing Period.");
        getContentPane().add(bp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 261, 80, -1));

        bpbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpbxActionPerformed(evt);
            }
        });
        getContentPane().add(bpbx, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 258, 383, -1));

        sb.setText("Services bought.");
        getContentPane().add(sb, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 332, 105, -1));

        noj.setText("No of Janitors.");
        getContentPane().add(noj, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 393, 80, 20));
        getContentPane().add(nojbx, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 393, 184, -1));

        cc.setText("Charges calculation.");
        getContentPane().add(cc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 431, 80, -1));

        Ccbx.setColumns(20);
        Ccbx.setRows(5);
        jScrollPane3.setViewportView(Ccbx);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 431, 383, -1));

        ta.setText("Total Amount.");
        getContentPane().add(ta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 548, 80, -1));
        getContentPane().add(tabx, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 545, 383, -1));

        bd.setText("Billing date.");
        getContentPane().add(bd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 589, 105, -1));
        getContentPane().add(bdbx, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 583, 383, -1));

        submit.setText("SUBMIT");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 609, 117, -1));

        bck.setText("<back");
        bck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bckActionPerformed(evt);
            }
        });
        getContentPane().add(bck, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 609, -1, -1));

        sbbx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ordinary janitorial services.", "Special service.", "Special and ordinary both.", " ", " " }));
        getContentPane().add(sbbx, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 326, 383, -1));

        jLabel11.setText("Select  services bought by customer.");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 304, 236, -1));

        jLabel2.setText("search customer.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 151, 105, -1));

        jButton1.setText("search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 147, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itp/image/log.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 21, 464, 69));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itp/image/b2.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bckActionPerformed
        MainFinance mainfinance= new MainFinance();
        mainfinance.setVisible(true);
        this.dispose();    // TODO add your handling code here:
    }//GEN-LAST:event_bckActionPerformed

    private void cidbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidbxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cidbxActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
      String cn = cnbx.getText();
      String ci = cidbx.getText();
      String bP = bpbx.getText();
      String sbr = sbbx.getSelectedItem().toString();
      String noJ = nojbx.getText();
      String cC = Ccbx.getText();
      String tam = tabx.getText();
      String bD = bdbx.getText();
      
      
      
        
      
      
      
   try   {
      
       String q = "INSERT INTO cb (cname,cid,bp,sb,noj,cc,ta,bd) values ('"+cn+"','"+ci+"','"+bP+"','"+sbr+"','"+noJ+"','"+cC+"','"+tam+"','"+bD+"')";
      pst = conn.prepareStatement(q);
      pst.execute();
    }catch (Exception e) {
        System.out.println(e);
    }
     cnbx.setText("");
        cidbx.setText("");
        bpbx.setText("");
        
        nojbx.setText("");
        Ccbx.setText("");
        tabx.setText("");
        bdbx.setText(""); 
   
   
   
   
   
   
   
    }//GEN-LAST:event_submitActionPerformed

    private void bpbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpbxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bpbxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    new jobSearchCus();
            
        //new 
        /*try{String name = searchbx.getText();
     String sql = "Select CusID,Title,Fname,Lname,NIC,Ad1,Ad2,City,Gender,Mobile,office,email,Type,Level,Tariff,PReason from customer where Fname LIKE'%"+name+"%'";
     pst = conn.prepareStatement(sql);
     rs = pst.executeQuery();
     }catch(SQLException e){
     
     }*/
     
     
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            //java.util.logging.Logger.getLogger(finance3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            //java.util.logging.Logger.getLogger(finance3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            //java.util.logging.Logger.getLogger(finance3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            //java.util.logging.Logger.getLogger(finance3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerBills().setVisible(true);
            }
        });
    }





    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Ccbx;
    private javax.swing.JButton bck;
    private javax.swing.JLabel bd;
    private javax.swing.JTextField bdbx;
    private javax.swing.JLabel bp;
    private javax.swing.JTextField bpbx;
    private javax.swing.JLabel cc;
    private javax.swing.JLabel cid;
    private javax.swing.JTextField cidbx;
    private javax.swing.JLabel cname;
    private javax.swing.JTextField cnbx;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel noj;
    private javax.swing.JTextField nojbx;
    private javax.swing.JLabel sb;
    private javax.swing.JComboBox sbbx;
    private javax.swing.JButton submit;
    private javax.swing.JLabel ta;
    private javax.swing.JTextField tabx;
    // End of variables declaration//GEN-END:variables
}

//  /  private static class con {
//
//        private static PreparedStatement preparedStatement(String q) {
//            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//        }
//
//        public con() {
//        }
//    }
//}


