/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.itp.customer.management;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author CHATHURAAKSHA
 */
public class Tarrif extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs1;
    public Tarrif() {
        initComponents();
        con = DBconnect.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        NIC = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jKeyword = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        l1 = new javax.swing.JLabel();
        jCusID = new javax.swing.JLabel();
        jName = new javax.swing.JLabel();
        jType = new javax.swing.JLabel();
        jLevel = new javax.swing.JLabel();
        jtarrif = new javax.swing.JLabel();
        jTarrif = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Customer Tarrif");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        NIC.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        NIC.setForeground(new java.awt.Color(0, 102, 102));
        NIC.setText("Cus ID");
        getContentPane().add(NIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Customer Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("CustomerType");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Customer Level");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("Customer Tarrif");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itp/image/log.png"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 490, 40));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 102, 102));
        jLabel16.setText("Enter Customer ID");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

        jKeyword.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jKeyword.setForeground(new java.awt.Color(0, 102, 102));
        getContentPane().add(jKeyword, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 80, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, -1, -1));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 102));
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, -1, -1));

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 102, 102));
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, -1, -1));

        jButton4.setForeground(new java.awt.Color(0, 102, 102));
        jButton4.setText("Logout");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, -1, -1));

        l1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        l1.setForeground(new java.awt.Color(0, 102, 102));
        getContentPane().add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 60, 20));

        jCusID.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jCusID.setForeground(new java.awt.Color(0, 102, 102));
        getContentPane().add(jCusID, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 70, 20));

        jName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jName.setForeground(new java.awt.Color(0, 102, 102));
        getContentPane().add(jName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 70, 20));

        jType.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jType.setForeground(new java.awt.Color(0, 102, 102));
        getContentPane().add(jType, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 100, 20));

        jLevel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLevel.setForeground(new java.awt.Color(0, 102, 102));
        jLevel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLevelKeyReleased(evt);
            }
        });
        getContentPane().add(jLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 130, 20));

        jtarrif.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jtarrif.setForeground(new java.awt.Color(0, 102, 102));
        jtarrif.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtarrifKeyReleased(evt);
            }
        });
        getContentPane().add(jtarrif, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 100, 20));

        jTarrif.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTarrif.setForeground(new java.awt.Color(0, 102, 102));
        getContentPane().add(jTarrif, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 90, 20));

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 102, 102));
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itp/image/b2.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 410));

        setSize(new java.awt.Dimension(611, 423));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         try {
            String str = jKeyword.getText();
            
            Connection con2 = DBconnect.connect();
        //String sqlq="select * from employees where fe1="+jTextField1.getText();
            String sqlstsmt = str;
            //To remove previously added rows
            PreparedStatement pst = con2.prepareStatement(sqlstsmt);
            rs1 = pst.executeQuery("select * from customer where CusID='"+str+"'");
            
            while(rs1.next()){
            
            jCusID.setText(rs1.getString("CusID"));
            jName.setText(rs1.getString("FName"));
            jType.setText(rs1.getString("Type"));
            jLevel.setText(rs1.getString("Level"));
            String m =rs1.getString("Level");
            
           






            if(m.equals("Default Customer")){
                System.out.println(m);
            jtarrif.setText("No Discount");
            }
            else if (m.equals("Level 1")){
            jtarrif.setText("5%");
            
            }
            else if (m.equals("Level 2")){
            jtarrif.setText("7%");
            
            }
            else if (m.equals("Level 3")){
            jtarrif.setText("9%");
            
            }
            else if (m.equals("Level 4")){
            jtarrif.setText("10%");
           
            
            }
            
            else if (m.equals("Level 5")){
            jtarrif.setText("12%");
            
            }
            else if (m.equals("Level 6")){
            jtarrif.setText("12.5%");
            
            }
            else if (m.equals("Level 7")){
            jtarrif.setText("15%");
            
            }
            
            else if (m.equals("Level 8")){
            jtarrif.setText("17.5%");
            
            }
            else if (m.equals("Level 9")){
            jtarrif.setText("19.75%");
            
            }
            else if (m.equals("Level 10")){
            jtarrif.setText("20%");
            
            }
            else if (m.equals("Inner Circle Customer")){
            jtarrif.setText("22%");
            
            }
            else if (m.equals("Bronze Customer")){
            jtarrif.setText("23%");
            
            }
            else if (m.equals("Silver Customer")){
            jtarrif.setText("23.5%");
            
            }
            else if (m.equals("Gold Customer")){
            jtarrif.setText("25%");
            
            }
            else if (m.equals("Platinum Customer")){
            jtarrif.setText("25.5%");
            
            }
            
            else {
                 jtarrif.setText("Ops Somthing Wrong with Data");
            }
            }
            //String kword="lab";
//            String sqlstsmt;
//            rs=sqlstsmt.executeQuery();
//            String sqlstsmt = "select CusID,FName,Type,Level from customer where CusID like '%" + kword + "%'";
            
//            jCusID.getText();
//            jName.getText();
//            jType.getText();
//            jLevel.getText();
            
            //String sqlstsmt="select * from jobs where location like '%lab%'";
            //FillTable(jTable_tableitp, sqlstsmt);
          //  FillLable();
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
          this.setVisible(false);
                    new Login().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jtarrifKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtarrifKeyReleased
    }//GEN-LAST:event_jtarrifKeyReleased

    private void jLevelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLevelKeyReleased
      String S= jLevel.getText();
        
        if(S.equals("Level 1")){
            jtarrif.setText("5%");
        }
        else
        {
            System.out.println("Something wrong");
        }
    }//GEN-LAST:event_jLevelKeyReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         this.setVisible(false);
        new Admin().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
           jCusID.setText("");
        jName.setText("");
        
        
        jType.setText("");
        jLevel.setText("");
        jtarrif.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tarrif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tarrif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tarrif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tarrif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tarrif().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NIC;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jCusID;
    private javax.swing.JTextField jKeyword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLevel;
    private javax.swing.JLabel jName;
    private javax.swing.JLabel jTarrif;
    private javax.swing.JLabel jType;
    private javax.swing.JLabel jtarrif;
    private javax.swing.JLabel l1;
    // End of variables declaration//GEN-END:variables
}
