/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.itp.inventory.management;

import com.toedter.calendar.JDateChooser;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.DatePicker;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import org.itp.customer.management.CleanManagementSystem;

/**
 *
 * @author ASUS
 */
public class SupplierDetails extends javax.swing.JFrame {

    PreparedStatement pst=null;
    Connection con=DbConnect.connect();
    ResultSet rs=null;
      
    /**
     * Creates new form SupplierDetails
     */
    public SupplierDetails() {
        initComponents();
         con=DbConnect.connect();
        tableLoad();
        setCombobox();
    }
    
    
    public void setCombobox() {
        try {

            Statement stmt = con.createStatement();
            String quer = "Select * from supplier_details_management";
            ResultSet rs = stmt.executeQuery(quer);

            while (rs.next()) {
                ItemCodecmb.addItem(rs.getString("Item_Code"));
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error");
        }
    }
    
     public void setCombobox2() {
        try {

            Statement stmt = con.createStatement();
            String quer = "Select * from supplier_details_management";
            ResultSet rs = stmt.executeQuery(quer);

            while (rs.next()) {
                ItemCodecmb.addItem(rs.getString("Item_Name"));
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Supplier_ID = new javax.swing.JTextField();
        Supplier_Name = new javax.swing.JTextField();
        Quantitytxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        CostPerItemtxt = new javax.swing.JTextField();
        ItemCodecmb = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ContactNumbertxt = new javax.swing.JTextField();
        Emailtxt = new javax.swing.JTextField();
        Addresstxt = new javax.swing.JTextField();
        SupplyDatetxt1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        ItemNamecmb = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        Inventory_Details = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Addbtn = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Deletebtn = new javax.swing.JButton();
        Searchbtn = new javax.swing.JButton();
        Printbtn = new javax.swing.JButton();
        Clearbtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        Demobtn = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Supplier Id");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Supplier Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Item Code");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Item Name");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Quantity");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Cost per Item");

        ItemCodecmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID45" }));
        ItemCodecmb.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ItemCodecmb.setInheritsPopupMenu(true);
        ItemCodecmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemCodecmbActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Supply Date");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Email");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Contact Number");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Address");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Emailtxt)
                    .addComponent(ContactNumbertxt)
                    .addComponent(Addresstxt)
                    .addComponent(SupplyDatetxt1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(SupplyDatetxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel9)
                        .addGap(7, 7, 7))
                    .addComponent(Emailtxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(ContactNumbertxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Addresstxt, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Supplier Details");

        ItemNamecmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Quantitytxt)
                            .addComponent(CostPerItemtxt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Supplier_Name)
                            .addComponent(Supplier_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ItemCodecmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ItemNamecmb, 0, 139, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel1)
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Supplier_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Supplier_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(ItemCodecmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(Quantitytxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(CostPerItemtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ItemNamecmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(18, 18, 18))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 101, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Main Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(831, 68, 196, -1));

        Inventory_Details.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Inventory_Details.setText("Inventory Details");
        Inventory_Details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inventory_DetailsActionPerformed(evt);
            }
        });
        getContentPane().add(Inventory_Details, new org.netbeans.lib.awtextra.AbsoluteConstraints(831, 111, 196, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "SuppireID", "SupplireName", "ItemCode", "ItemName", "Quantity", "SupplyDate", "Email", "ContactNo", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 892, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 470, -1, -1));

        Addbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Addbtn.setText("Add");
        Addbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddbtnMouseClicked(evt);
            }
        });
        Addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Addbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 742, 100, 33));

        Update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        getContentPane().add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 742, 100, 33));

        Deletebtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Deletebtn.setText("Delete");
        Deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletebtnActionPerformed(evt);
            }
        });
        getContentPane().add(Deletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 742, 103, 33));

        Searchbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Searchbtn.setText("Search");
        Searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Searchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 742, 99, 33));

        Printbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Printbtn.setText("Print");
        Printbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Printbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 742, 85, 33));

        Clearbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Clearbtn.setText("Clear");
        Clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Clearbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 742, 75, 33));
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(831, 154, 254, 242));

        Demobtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Demobtn.setText("Demo");
        Demobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DemobtnActionPerformed(evt);
            }
        });
        getContentPane().add(Demobtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(853, 742, 90, 33));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itp/image/log.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 11, 479, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itp/image/b2.jpg"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 880));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Inventory_DetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inventory_DetailsActionPerformed
        InventoryDetails id = new InventoryDetails();
        id.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Inventory_DetailsActionPerformed

    private void AddbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddbtnActionPerformed
        // TODO add your handling code here:
        String SupplierId = Supplier_ID.getText();
        String SupplierName = Supplier_Name.getText();
        String ItemCode = (String) ItemCodecmb.getSelectedItem();
        String ItemName = (String)ItemNamecmb.getSelectedItem();
        int Quantity = Integer.parseInt(Quantitytxt.getText());
        double CostPerItem = Double.parseDouble(CostPerItemtxt.getText());
         java.util.Date s = SupplyDatetxt1.getDate();
        //String SupplierDate = ((JTextField) this.SupplyDatetxt.getDateEditor().getUiComponent()).getText();
        String Email = Emailtxt.getText();
        int ContactNumber = Integer.parseInt(ContactNumbertxt.getText());
        String Address = Addresstxt.getText();
  
    
        try {
            System.out.println("feadf");

            String qry = "insert into supplier_details_management  (Supplier_ID,Supplier_Name,Item_Code,Item_Name,Quantity,Cost_per_Item,Supply_date,Email,Contact_No,Address) values(?,?,?,?,?,?,?,?,?,?)"; //('"+ this.itemcodetxt.getText() +"', '"+ this.ItemNametxt.getText() +"', '"+ aveilableQuantity +"', '"+ Stock +"', '"+ CostPerItem +"', '"+ this.Supplier_Nametxt.getText()+"', '"+ this.expiredate.getDateEditor().getUiComponent()).getText() +"', '"+ this.issuedate.getDateEditor().getUiComponent()).getText();+"','"+ this.Customer_Nametxt.getText()+"')";
            
            pst = con.prepareStatement(qry);
            
            pst.setString(1, SupplierId);
            pst.setString(2, SupplierName);
            pst.setString(3, ItemCode);
            pst.setString(4, ItemName);
            pst.setInt(5, Quantity);
            pst.setDouble(6, CostPerItem);
            pst.setDate(7,convertJavaDateToSqlDate(s) );
            pst.setString(8, Email);
            pst.setInt(9, ContactNumber);
            pst.setString(10, Address);

            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Saved");
               
        }
        catch(Exception e){
            System.out.println(e);
        }

    }//GEN-LAST:event_AddbtnActionPerformed
    public java.sql.Date convertJavaDateToSqlDate(java.util.Date date) {
    return new java.sql.Date(date.getTime());
}   
    
    private void DeletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletebtnActionPerformed
        // TODO add your handling code here:
         int rep = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to Delete this row", "confirm", JOptionPane.YES_NO_CANCEL_OPTION);
        if (rep == JOptionPane.YES_OPTION) {
           String quary= "delete from supplier_details_management where Supplier_ID='" + Supplier_ID.getText()+"'";
            try {
                pst = con.prepareStatement(quary);
                //int eavailable=
                pst.execute();
                JOptionPane.showMessageDialog(rootPane, "Row deleted", "", JOptionPane.INFORMATION_MESSAGE);
              //  new schedulemain();
                //this.dispose();

                //System.out.println(sqlq);
            } catch (Exception e) {
                System.err.print(e);
                JOptionPane.showMessageDialog(rootPane, "job deletion failure", "Error", JOptionPane.ERROR_MESSAGE);
            }
             new SupplierDetails().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_DeletebtnActionPerformed

    private void ClearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearbtnActionPerformed
        // TODO add your handling code here:
        this.Supplier_ID.setText(null);
        this.Supplier_Name.setText(null);
        this.ItemCodecmb.getSelectedItem();
        this.ItemNamecmb.getSelectedItem();
        this.Quantitytxt.setText(null);
        this.CostPerItemtxt.setText(null);
        ((JTextField) this.SupplyDatetxt1.getDateEditor().getUiComponent()).setText(null);
        //((JTextField)this.issuedate.getDateEditor().getUiComponent()).setText(null);
        //this.expiredate.setText(null);
        //this.issuedate.setText(null);
        this.Emailtxt.setText(null);
        this.ContactNumbertxt.setText(null);
        this.Addresstxt.setText(null);


    }//GEN-LAST:event_ClearbtnActionPerformed

    private void ItemCodecmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemCodecmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemCodecmbActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
       
      /* // update
        //UPDATE table_name SET column1=value1,column2=value2,... WHERE some_column=some_value;
        //String cid=jTextField1.getText()
        java.sql.Date d1=convertJavaDateToSqlDate(SupplyDatetxt1.getDate());
        //java.sql.Date d2=convertJavaDateToSqlDate(issuedate.getDate());
        String SupplierID = Supplier_ID.getText();
        String SupplierName= Supplier_Name.getText();
        int AvalibleQuantity= Integer.parseInt(Available_Quantitytxt.getText());
       // gpr = Double.parseDouble(eneed)*spr*1.15;

        String sqlq= "update supplier_details_management set Supplier_ID='" +Supplier_ID + "', Supplier_Name='" +Supplier_Name + "',Item_Code='" +ItemCodecmb+ "',"
                + "Item_Name ='" +Integer.parseInt(stocktxt.getText())+ "',Cost_Per_Item='" +Double.parseDouble(Cost_Per_Itemtxt.getText())+ "', Supplier_name='" +Supplier_Nametxt.getText() +"',Expire_Date='" +d1+ "',"
                + " Issue_Date='" +d2+"', Customer_Name='" +Customer_Nametxt.getText()+"' where Item_Code='" +ItemCode +"'";

        int rep = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want ot update this job?", "Confirm", JOptionPane.YES_NO_CANCEL_OPTION);
        if (rep == JOptionPane.YES_OPTION) {
            try {

                pst = con.prepareStatement(sqlq);
                pst.execute(sqlq);
                JOptionPane.showMessageDialog(rootPane, "InventoryDetails updated successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                new InventoryDetails().setVisible(true);
                tableLoad();
                this.dispose();

            } catch (Exception e) {
                System.out.print(e);
                JOptionPane.showMessageDialog(rootPane, "InventoryDetails update failed", "Error", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }  

               
*/

    }//GEN-LAST:event_UpdateActionPerformed

    private void AddbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddbtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AddbtnMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        try{
            
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
        int r = jTable1.getSelectedRow();
        String SupplireID =jTable1.getValueAt(r,0). toString();
        String SupplireName =jTable1.getValueAt(r,1). toString();
        String ItemCode =jTable1.getValueAt(r,2). toString();
        String ItemName =jTable1.getValueAt(r,3). toString();
        String Quantity =jTable1.getValueAt(r,4). toString();
        String Cost_per_Item =jTable1.getValueAt(r,5). toString();
       // Date Supply_Date =(Date)jTable1.getValueAt(r,6);
       String DDate=model.getValueAt(r, 6).toString();
       
       try{
        java.util.Date date1=new SimpleDateFormat("yyyy-MM-dd").parse(DDate);
        //String sd2=dateFormat.format(date1);
        SupplyDatetxt1.setDate(date1);
       }
       catch(Exception e){
            JOptionPane.showMessageDialog(null, "invalide Date format");
        }
        
        String Email =jTable1.getValueAt(r,7). toString();
        String Contact_Number =jTable1.getValueAt(r,8). toString();
        String Address =jTable1.getValueAt(r,9). toString();
        
        Supplier_ID.setText(SupplireID);
        Supplier_Name.setText(SupplireName);
        ItemCodecmb.setSelectedItem(ItemCode);
       // Item_Nametxt.setText(ItemName);
        Quantitytxt.setText(Quantity);
        CostPerItemtxt.setText(Cost_per_Item);
        //SupplyDatetxt.setDate(Supply_Date);
        Emailtxt.setText(Email);
        ContactNumbertxt.setText(Contact_Number);
        Addresstxt.setText(Address);
        }
        
        catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void SearchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchbtnActionPerformed
        // TODO add your handling code here:
         //if()
        try {

            String SupplierID = Supplier_ID.getText();
            String SupplierName = Supplier_Name.getText();
            
            String qry = "select * from supplier_details_management where Supplier_ID = '" +SupplierID+ "' and Supplier_Name ='" +SupplierName+ "'";
            
            pst = con.prepareStatement(qry);
           // pst.setString(1, Supplier_ID.getText());
           // pst.setString(2, Supplier_Name.getText());
            rs = pst.executeQuery();
//            tableLoad(jTable1, qry);

            if(rs.next()){
                JOptionPane.showMessageDialog(null, "hiiiiiiiiiiiii");
                String a = rs.getString("Supplier_ID");
                Supplier_ID.setText(a);
                String b = rs.getString("Supplier_Name");
                Supplier_Name.setText(b);
                String c = rs.getString("Item_Code");
               // ItemCodecmb.setText(c);
                String d = rs.getString("Item_Name");
             //   Item_Nametxt.setText(d);
                String e = rs.getString("Quantity");
                Quantitytxt.setText(e);
                String f= rs.getString("Cost_per_Item");
                CostPerItemtxt.setText(f);
                Date g = rs.getDate("Supply_date");
                SupplyDatetxt1.setDate(g);
                String h = rs.getString("Email");
                Emailtxt.setText(h);
                String i = rs.getString("Contact_No");
                ContactNumbertxt.setText(i);
                String j= rs.getString("Address");
                Addresstxt.setText(j);
                System.out.println("ok111");
            }

        } catch (Exception e) {

            // 
        }


        
    }//GEN-LAST:event_SearchbtnActionPerformed

    private void PrintbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintbtnActionPerformed
      
                try {
                    boolean complete=jTable1.print();
                    if(complete){
                        
                        JOptionPane.showMessageDialog(null, "Done Printing...");
                        
                    }
                    else{
                        
                        JOptionPane.showMessageDialog(null, "Printing...");
                    }   } catch (PrinterException ex) {
                    Logger.getLogger(SupplierDetails.class.getName()).log(Level.SEVERE, null, ex);
                }
        
        
         
    }//GEN-LAST:event_PrintbtnActionPerformed

    private void DemobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DemobtnActionPerformed
        // TODO add your handling code here:
        
        Supplier_ID.setText("213");
        java.util.Date date1=new java.util.Date();
        Supplier_Name.setText("daad");
       // ItemCodecmb.setSelectedItem(1);
        //ItemNamecmb.setSelectedItem(2);
        Quantitytxt.setText("");
        CostPerItemtxt.setText("");
        SupplyDatetxt1.setDate(date1);
        Emailtxt.setText("");
        ContactNumbertxt.setText("");
        Addresstxt.setText("");
        
        
    }//GEN-LAST:event_DemobtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CleanManagementSystem cm=new CleanManagementSystem();
        cm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SupplierDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SupplierDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SupplierDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SupplierDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SupplierDetails().setVisible(true);
                // new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addbtn;
    private javax.swing.JTextField Addresstxt;
    private javax.swing.JButton Clearbtn;
    private javax.swing.JTextField ContactNumbertxt;
    private javax.swing.JTextField CostPerItemtxt;
    private javax.swing.JButton Deletebtn;
    private javax.swing.JButton Demobtn;
    private javax.swing.JTextField Emailtxt;
    private javax.swing.JButton Inventory_Details;
    private javax.swing.JComboBox<String> ItemCodecmb;
    private javax.swing.JComboBox<String> ItemNamecmb;
    private javax.swing.JButton Printbtn;
    private javax.swing.JTextField Quantitytxt;
    private javax.swing.JButton Searchbtn;
    private javax.swing.JTextField Supplier_ID;
    private javax.swing.JTextField Supplier_Name;
    private com.toedter.calendar.JDateChooser SupplyDatetxt1;
    private javax.swing.JButton Update;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void tableLoad() {
     //  throw new UnsupportedOperationException("Not supported yet.");
        //To change body of generated methods, choose Tools | Templates.
         try{
            String qry = "select * from supplier_details_management";
            pst = con.prepareStatement(qry);
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        } 
         
         catch (Exception e) {
            System.out.println(e);
            
        }
    
    }
}
