/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.itp.transport.handling;

import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author LAKVI
 */
public class Getjob extends javax.swing.JFrame {
     Connection conn=null;
    PreparedStatement pst=null;
     
    ResultSet rs = null;

    /**
     * Creates new form Getjob
     */
    public Getjob() {
        initComponents();
         conn = dbcoonnect.connect();
        
        setSize(1500, 1000);
        
        tableload();
        
        fillcombo();
    }

    
     public void tableload() 
    {
        try {
            String sql = "SELECT * FROM empassigned";
         pst =(PreparedStatement) conn.prepareStatement(sql);
        
          rs=pst .executeQuery();
          
          jTable1.setModel(DbUtils.resultSetToTableModel(rs));
    
        }
        catch (Exception e) 
        {
        }
    }
     
     private void fillcombo()
     {
         try {
             String sql1 = "SELECT * FROM vehivle ";
             pst= (PreparedStatement)  conn.prepareStatement(sql1);
             rs=pst .executeQuery(); 
             
             while (rs.next()){
             String vnum = rs.getString("Vehi_Num");
             
             vnumcbox.addItem(vnum);
             }
         } catch (Exception e) {
         }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        completecombo = new javax.swing.JToggleButton();
        vnumcbox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jid = new javax.swing.JTextField();
        jd = new javax.swing.JTextField();
        ep = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe Script", 1, 36)); // NOI18N
        jLabel1.setText("Get Jobs");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(470, 10, 190, 59);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jTable1.setRowHeight(20);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(340, 190, 760, 300);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(100, 210, 100, 30);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(140, 150, 130, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Name");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 150, 80, 30);

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(1120, 540, 90, 40);

        completecombo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        completecombo.setText("Complete");
        completecombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completecomboActionPerformed(evt);
            }
        });
        getContentPane().add(completecombo);
        completecombo.setBounds(110, 560, 120, 30);

        vnumcbox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        vnumcbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vnumcboxActionPerformed(evt);
            }
        });
        getContentPane().add(vnumcbox);
        vnumcbox.setBounds(160, 470, 120, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Job ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 274, 120, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Job Date");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 314, 120, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Employee Pass");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 360, 110, 30);

        jid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jidActionPerformed(evt);
            }
        });
        getContentPane().add(jid);
        jid.setBounds(170, 260, 150, 30);
        getContentPane().add(jd);
        jd.setBounds(170, 310, 150, 30);
        getContentPane().add(ep);
        ep.setBounds(170, 360, 150, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Vehi num");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 470, 80, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String name = jTextField4.getText();

        String sql = "SELECT  empID,jobID FROM empjobs where empID Like '"+name+"' ";
        try {
            pst =(PreparedStatement) conn.prepareStatement(sql);

            rs =  pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        transportmain m1=new transportmain();
        m1 . setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void completecomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completecomboActionPerformed
        // TODO add your handling code here:
        //String  id = vnumcbox.getSelectedItem().toString();
        
        int x= JOptionPane.showConfirmDialog(null,"Do You Realy Want To Update");
       
       if(x==0)
       {
        String id = jid.getText();
        String date=jd.getText();
        String emp_pass=ep.getText();
        String vnum =vnumcbox.getSelectedItem().toString();
        
        try{
            String val1, q="select jobid as vv from empassigned";
            pst = (PreparedStatement) conn.prepareStatement(q);
            rs=pst.executeQuery(q);
            while(rs.next()){
                val1=rs.getString("vv");
                System.out.println(val1);
                if(id.compareToIgnoreCase(val1)==0){
                    JOptionPane.showMessageDialog(rootPane, "Alredy Completed");
                    return;
                }
            }
            
        }
        catch(Exception e){
            
        }
           
           String sql = "UPDATE empassigned SET jobid ='"+id+"', jdate = '"+date+"',empass= '"+emp_pass+"',Vehi_Num = '"+vnum+"',stat='Complete' where jobid ='"+id+"'";
           try {
               pst= (PreparedStatement)  conn.prepareStatement(sql);
               
               pst.execute();
               
               tableload();
           } 
           catch (Exception e) 
           {
           }
       }
    }//GEN-LAST:event_completecomboActionPerformed

    private void vnumcboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vnumcboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vnumcboxActionPerformed

    private void jidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jidActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int r = jTable1.getSelectedRow();
        
        String id=jTable1.getValueAt(r, 0).toString();
        String name=jTable1.getValueAt(r, 1).toString();
        String add=jTable1.getValueAt(r, 2).toString();
        String cnum=jTable1.getValueAt(r, 3).toString();
        
        jid.setText(id);
        jd.setText(name);
        ep.setText(add);
        
      

    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Getjob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Getjob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Getjob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Getjob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Getjob().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton completecombo;
    private javax.swing.JTextField ep;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jd;
    private javax.swing.JTextField jid;
    private javax.swing.JComboBox vnumcbox;
    // End of variables declaration//GEN-END:variables
}
