/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.itp.openems.ui;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
import org.itp.commons.Constants;
import org.itp.commons.DBConnect;
import org.itp.commons.DBUtils;
import org.itp.commons.Queries;
import org.itp.commons.Validation;

/**
 *
 * @author THISURA THEJITH
 */
public class Appraisals extends javax.swing.JFrame {

    /**
     * Creates new form Appraisals
     */
    public Appraisals() {
        initComponents();
        tableload();
        updateBtn.setEnabled(false);
    }
    public void tableload(){
        try{
        
        Connection connect = new DBConnect(Constants.USER, Constants.PASSWORD).getConnection();
        PreparedStatement preparedStatement = connect.prepareStatement(Queries.EMS.Select.GET_APPRAISAL_TABLE);
        ResultSet resultset = preparedStatement.executeQuery();
        appraisalTable.setModel(DbUtils.resultSetToTableModel(resultset));
        }catch (SQLException e){
            System.out.println(e);
        }
    }
    
    public void tableload(String keyword) {
        try {
            Connection connect = new DBConnect(Constants.USER, Constants.PASSWORD).getConnection();
            
            PreparedStatement preparedStatement = connect.prepareStatement(Queries.EMS.Select.SEARCH_APPRAISALS);
            for (int i = 1; i < 7; i++) {
                preparedStatement.setString(i, "%" + keyword + "%");
            }
            ResultSet resultset = preparedStatement.executeQuery();
            while (appraisalTable.getRowCount() > 0) {
                ((DefaultTableModel) appraisalTable.getModel()).removeRow(0);
            }
            int columns = resultset.getMetaData().getColumnCount();
            while (resultset.next()) {
                Object[] row = new Object[columns];
                for (int i = 1; i <= columns; i++) {
                    row[i - 1] = resultset.getObject(i);
                }
                ((DefaultTableModel) appraisalTable.getModel()).insertRow(resultset.getRow() - 1, row);
            }

            resultset.close();
        } catch (SQLException e) {

        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        demoBtn = new javax.swing.JButton();
        insertBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        appraisalTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        searchTxt = new javax.swing.JTextField();
        searchkBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        nicLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nicTxt = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        bonusLbl = new javax.swing.JLabel();
        bonusTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        reviewsLbl = new javax.swing.JLabel();
        reviewsTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Appraisals");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        demoBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        demoBtn.setText("Demo");
        demoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                demoBtnActionPerformed(evt);
            }
        });
        jPanel1.add(demoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 22, -1, 34));

        insertBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        insertBtn.setText("Insert");
        insertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertBtnActionPerformed(evt);
            }
        });
        jPanel1.add(insertBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 22, -1, 34));

        updateBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        jPanel1.add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 22, -1, 34));

        backBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 22, -1, 34));

        clearBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        jPanel1.add(clearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 22, -1, 34));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itp/image/b1.jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 440, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 460, 80));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Appraisal details"));

        appraisalTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        appraisalTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appraisalTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(appraisalTable);

        jLabel2.setText("Search Keyword");

        searchkBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        searchkBtn.setText("Search Key");
        searchkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchkBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchkBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(searchkBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, -1, 300));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itp/image/log.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 11, 475, 78));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Appraisal"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nicLbl.setForeground(new java.awt.Color(255, 0, 51));
        jPanel3.add(nicLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 150, 20));

        jLabel1.setText("NIC No");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        nicTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nicTxtMouseClicked(evt);
            }
        });
        jPanel3.add(nicTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 157, -1));

        searchBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        jPanel3.add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, 31));

        bonusLbl.setForeground(new java.awt.Color(255, 0, 51));
        jPanel3.add(bonusLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 157, 20));

        bonusTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                bonusTxtFocusLost(evt);
            }
        });
        jPanel3.add(bonusTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 157, -1));

        jLabel3.setText("Bonus");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        reviewsLbl.setForeground(new java.awt.Color(255, 0, 51));
        jPanel3.add(reviewsLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 150, 20));
        jPanel3.add(reviewsTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 157, -1));

        jLabel5.setText("Reviews");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, 20));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 350, 250));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itp/image/b2.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed
    int employeeID = 0;
    int appraisalID = 0;
    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        updateBtn.setEnabled(true);
        insertBtn.setEnabled(false);
        nicLbl.setText(null);
        clear();
        if (nicTxt.getText().isEmpty()) {
            nicLbl.setText("*Enter the NIC No");
            JOptionPane.showMessageDialog(null, "Please enter the NIC No", "Error", JOptionPane.ERROR_MESSAGE);
            updateBtn.setEnabled(false);
            insertBtn.setEnabled(true);
        } else {
            try {
                if (!Validation.ValidNIC(this.nicTxt.getText())) {
                    nicLbl.setText("*Invalid NIC No");
                    JOptionPane.showMessageDialog(null, "The NIC No is invalid", "Error", JOptionPane.ERROR_MESSAGE);
                    updateBtn.setEnabled(false);
                    insertBtn.setEnabled(true);
                } else if (Validation.ValidNIC(this.nicTxt.getText())) {
                    clear();
                    Connection connect = new DBConnect(Constants.USER, Constants.PASSWORD).getConnection();
                    PreparedStatement preparedStatement = connect.prepareStatement(Queries.EMS.Select.GET_EMPLOYEE_ID_BY_NIC);
                    preparedStatement.setString(1, this.nicTxt.getText());
                    ResultSet resultset = preparedStatement.executeQuery();
                    int count = 0;
                    while (resultset.next()) {
                        employeeID = resultset.getInt("EmployeeID");
                        count++;
                    }
                    if (count == 0) {
                        JOptionPane.showMessageDialog(null, "An employee with this NIC No is not registered", "Error", JOptionPane.ERROR_MESSAGE);
                        updateBtn.setEnabled(false);
                        insertBtn.setEnabled(true);
                        return;
                    }
                    resultset.close();
                    preparedStatement.close();
                    connect = new DBConnect(Constants.USER, Constants.PASSWORD).getConnection();
                    preparedStatement = connect.prepareStatement(Queries.EMS.Select.GET_APPRAISAL_BY_EMPLOYEE_ID);
                    preparedStatement.setInt(1, employeeID);
                    resultset = preparedStatement.executeQuery();
                    int count1 = 0;
                    while (resultset.next()) {
                        this.bonusTxt.setText(resultset.getString("Bonus"));
                        this.reviewsTxt.setText(resultset.getString("Reviews"));
                        count1++;
                    }
                    if (count1 == 0) {
                        JOptionPane.showMessageDialog(null, "An appraisal for this employee is not present", "Error", JOptionPane.ERROR_MESSAGE);
                        updateBtn.setEnabled(false);
                        return;
                    }
                    resultset.close();
                    preparedStatement.close();
                }

            } catch (SQLException e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        nicLbl.setText(null);
                
        if (nicTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "No employee to update", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (bonusTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please insert the bonus amount for the employee", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!Validation.ValidDigits(this.bonusTxt.getText())) {
            bonusLbl.setText("*Invalid bonus");
            JOptionPane.showMessageDialog(null, "The bonus is invalid", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (Double.parseDouble(this.bonusTxt.getText()) < 0) {
            JOptionPane.showMessageDialog(null, "Bonus cannot be negative", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            bonusLbl.setText(null);
            try {
                Connection connect = new DBConnect(Constants.USER, Constants.PASSWORD).getConnection();
                PreparedStatement preparedStatement = connect.prepareStatement(Queries.EMS.Select.GET_EMPLOYEE_ID_BY_NIC);
                preparedStatement.setString(1, this.nicTxt.getText());
                ResultSet resultset = preparedStatement.executeQuery();
                int count = 0;
                while (resultset.next()) {
                    employeeID = resultset.getInt("EmployeeID");
                    count++;
                }
                if (count == 0) {
                    JOptionPane.showMessageDialog(null, "You haven't pressed the search button.An employee with this NIC No doesn't exist", "Error", JOptionPane.ERROR_MESSAGE);
                    clear();
                    return;
                }
                connect = new DBConnect(Constants.USER, Constants.PASSWORD).getConnection();
                preparedStatement = connect.prepareStatement(Queries.EMS.Select.GET_APPRAISAL_ID_BY_EMPLOYEE_ID);
                preparedStatement.setInt(1, employeeID);
                resultset = preparedStatement.executeQuery();
                int count1 = 0;
                while (resultset.next()) {
                    appraisalID = resultset.getInt("AppraisalID");
                    count1++;
                }
                if (count1 == 0) {
                    JOptionPane.showMessageDialog(null, "Can't update a non-existing record", "Error", JOptionPane.ERROR_MESSAGE);
                    clear();
                    return;
                }

                resultset.close();
                preparedStatement.close();
                connect = new DBConnect(Constants.USER, Constants.PASSWORD).getConnection();
                preparedStatement = connect.prepareStatement(Queries.EMS.Update.APPRAISAL);
                preparedStatement.setString(1, this.bonusTxt.getText());
                preparedStatement.setString(2, this.reviewsTxt.getText());
                preparedStatement.setInt(3, employeeID);
                int affectedRows = preparedStatement.executeUpdate();
                System.out.println("affected rows=" + affectedRows);
                preparedStatement.close();
                JOptionPane.showMessageDialog(null, "Updated Successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                tableload();
                nicTxt.setText(null);
                clear();
                insertBtn.setEnabled(true);
                updateBtn.setEnabled(false);
            } catch (SQLException e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void insertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertBtnActionPerformed
        nicLbl.setText(null);
        if (nicTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "No employee to insert the appraisal", "Error", JOptionPane.ERROR_MESSAGE);
            clear();
            return;
        } else if (!Validation.ValidNIC(this.nicTxt.getText())) {
            nicLbl.setText("*Invalid NIC No");
            JOptionPane.showMessageDialog(null, "The NIC No is invalid", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        else {
            bonusLbl.setText(null);
            try {
                Connection connect = new DBConnect(Constants.USER, Constants.PASSWORD).getConnection();
                PreparedStatement preparedStatement = connect.prepareStatement(Queries.EMS.Select.GET_EMPLOYEE_ID_BY_NIC);
                preparedStatement.setString(1, this.nicTxt.getText());
                ResultSet resultset = preparedStatement.executeQuery();
                int count = 0;
                while (resultset.next()) {
                    employeeID = resultset.getInt("EmployeeID");
                    count++;
                }
                if (count == 0) {
                    JOptionPane.showMessageDialog(null, "An employee with this NIC No is not registered", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                resultset.close();
                preparedStatement.close();
                
                connect = new DBConnect(Constants.USER, Constants.PASSWORD).getConnection();
                preparedStatement = connect.prepareStatement(Queries.EMS.Select.GET_APPRAISAL_ID_BY_EMPLOYEE_ID);
                preparedStatement.setInt(1, employeeID);
                resultset = preparedStatement.executeQuery();
                int count1 = 0;
                while (resultset.next()) {
                    appraisalID = resultset.getInt("AppraisalID");
                    count1++;
                }
                if (count1 != 0) {
                    JOptionPane.showMessageDialog(null, "This employee already has an appraisal ", "Error", JOptionPane.ERROR_MESSAGE);
                    nicLbl.setText(null);
                    return;
                }

                resultset.close();
                preparedStatement.close();

                connect = new DBConnect(Constants.USER, Constants.PASSWORD).getConnection();
                preparedStatement = connect.prepareStatement(Queries.EMS.Select.GET_EMPLOYEE_ID_BY_NIC);
                preparedStatement.setString(1, this.nicTxt.getText());
                resultset = preparedStatement.executeQuery();
                int count2 = 0;
                while (resultset.next()) {
                    employeeID = resultset.getInt("EmployeeID");
                    count2++;
                }
                resultset.close();
                preparedStatement.close();
                
                
                if (bonusTxt.getText().isEmpty()){
                    bonusLbl.setText("*Insert the bonus amount");
                    JOptionPane.showMessageDialog(null, "You havent inserted the bonus of this employee", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                else if(!Validation.ValidDigits(this.bonusTxt.getText())){
                    bonusLbl.setText("*Invalid bonus");
                    JOptionPane.showMessageDialog(null, "The bonus is invalid", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                else if (Double.parseDouble(this.bonusTxt.getText()) < 0) {
                    bonusLbl.setText("*Bonus cannot be negative");
                    JOptionPane.showMessageDialog(null, "Bonus cannot be negative", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                
                connect = new DBConnect(Constants.USER, Constants.PASSWORD).getConnection();
                preparedStatement = connect.prepareStatement(Queries.EMS.Insert.APPRAISALS);
                preparedStatement.setInt(1, employeeID);
                preparedStatement.setString(2, this.bonusTxt.getText());
                preparedStatement.setString(3, this.reviewsTxt.getText());

                int affectedRows = preparedStatement.executeUpdate();
                System.out.println("affected rows=" + affectedRows);
                preparedStatement.close();
                JOptionPane.showMessageDialog(null, "Inserted Successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                tableload();
                clear();
            } catch (SQLException e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_insertBtnActionPerformed

    private void demoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_demoBtnActionPerformed
        this.nicTxt.setText("942811110v");
    }//GEN-LAST:event_demoBtnActionPerformed

    private void appraisalTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appraisalTableMouseClicked
        updateBtn.setEnabled(true);
        insertBtn.setEnabled(false);
        int i = appraisalTable.getSelectedRow();
        TableModel model = appraisalTable.getModel();
        nicTxt.setText(model.getValueAt(i, 3).toString());
        bonusTxt.setText(model.getValueAt(i, 5).toString());
        reviewsTxt.setText(model.getValueAt(i, 6).toString());
        insertBtn.setEnabled(false);
    }//GEN-LAST:event_appraisalTableMouseClicked

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        clear();
        updateBtn.setEnabled(false);
        insertBtn.setEnabled(true);
        nicTxt.setText(null);
        reviewsLbl.setText(null);
        bonusLbl.setText(null);
        searchTxt.setText(null);
        tableload();
    }//GEN-LAST:event_clearBtnActionPerformed

    private void nicTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nicTxtMouseClicked
        if(nicTxt.getText().isEmpty()){
            insertBtn.setEnabled(true);
        }
    }//GEN-LAST:event_nicTxtMouseClicked

    private void searchkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchkBtnActionPerformed
        if(this.searchTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Please enter a search keyword","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            String keyword = searchTxt.getText();
            tableload(keyword);
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_searchkBtnActionPerformed

    private void bonusTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bonusTxtFocusLost
        if (this.bonusTxt.getText().isEmpty()){
                bonusLbl.setText("*Insert the bonus amount");
        }
        else if(!Validation.ValidDigits(this.bonusTxt.getText())){
                bonusLbl.setText("*Invalid bonus");
        }
        else if (Double.parseDouble(this.bonusTxt.getText()) < 0) {
                bonusLbl.setText("*Bonus cannot be negative");
        }
        else{
                bonusLbl.setText(null);
        }
        
    }//GEN-LAST:event_bonusTxtFocusLost
    private void clear() {
        reviewsTxt.setText(null);
        bonusTxt.setText(null);
        nicLbl.setText(null);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Appraisals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Appraisals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Appraisals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Appraisals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Appraisals().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable appraisalTable;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel bonusLbl;
    private javax.swing.JTextField bonusTxt;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton demoBtn;
    private javax.swing.JButton insertBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nicLbl;
    private javax.swing.JTextField nicTxt;
    private javax.swing.JLabel reviewsLbl;
    private javax.swing.JTextField reviewsTxt;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JButton searchkBtn;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
